
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFybmV0dCIsImVtYWlsIjoiYmFybmV0dGJsYW5rZW5zaGlwQHF1b3RlemFydC5jb20iLCJyb2xlIjoidXNlciIsImlkIjoiYTNiOGQ0MjUtMmI2MC00YWQ3LWJlY2MtYmVkZjJlZjg2MGJkIiwiaWF0IjoxNTkzMDM2NTA1LCJleHAiOjE1OTMxMjI5MDV9.aHec9s6oh2bHyGBpwZxRaHio06fRDTeHOfEVUXFXApQ

###

GET http://localhost:3000/api/v1/users/id/e8fd159b-57c4-4d36-9bd7-a59ca13057bb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFybmV0dCIsImVtYWlsIjoiYmFybmV0dGJsYW5rZW5zaGlwQHF1b3RlemFydC5jb20iLCJyb2xlIjoidXNlciIsImlkIjoiYTNiOGQ0MjUtMmI2MC00YWQ3LWJlY2MtYmVkZjJlZjg2MGJkIiwiaWF0IjoxNTkzMDM2NDYwLCJleHAiOjE1OTMxMjI4NjB9.USwwBZZqA198P-kImdL379FZLL0vI52qnFws7CtNMp8

###
DELETE http://localhost:3000/api/v1/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFybmV0dCIsImVtYWlsIjoiYmFybmV0dGJsYW5rZW5zaGlwQHF1b3RlemFydC5jb20iLCJyb2xlIjoidXNlciIsImlkIjoiYTNiOGQ0MjUtMmI2MC00YWQ3LWJlY2MtYmVkZjJlZjg2MGJkIiwiaWF0IjoxNTkzMDM2NjM3fQ.9GnTx12UMRjc5bXsTmTgdfHa2qkrQG-30NVuoAYBBy8"
}

###
POST http://localhost:3000/api/v1/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFybmV0dCIsImVtYWlsIjoiYmFybmV0dGJsYW5rZW5zaGlwQHF1b3RlemFydC5jb20iLCJyb2xlIjoidXNlciIsImlkIjoiYTNiOGQ0MjUtMmI2MC00YWQ3LWJlY2MtYmVkZjJlZjg2MGJkIiwiaWF0IjoxNTkzMDM2NTA1fQ.GMrhLLx0L5bNTiBlpE41XvjLec_V01rm2VkhSX9gP4w"
}

###

POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "username": "Barnett",
    "email":"barnettblankenship@quotezart.com"
}

